### ISSUE TITLE
question: tcp_trsp: mutex unlock before write_event

### ISSUE THREAD

**Issue by furmur** [sipwise/sems#3]
core/sip/tcp_trsp.cpp

i wonder what's the reason to have functions:
`add_read_event_ul` and `add_write_event_ul` 

asking because got deadlock because of `sock_mut.unlock()` in `add_write_event_ul`

please, explain
thank you in advance

**Comment by apogrebennyk** [comment]
Hello,
the upstream of this project is https://github.com/sems-server/sems/, we as sipwise can't answer your questions because we are not using sems for tcp and we didn't write this code.

**Comment by apogrebennyk** [comment]
They also have discussion forums https://groups.google.com/forum/#!forum/sems-dev and https://groups.google.com/forum/#!forum/sems-users

**Comment by furmur** [comment]
@apogrebennyk  thank you
