### ISSUE TITLE
how to install from the sipwise git 

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sipwise/sems#5]
following the install procedure as described in the doc, I arrive at creating deb files. However when I do : 
root@sems:/usr/src# dpkg -i ngcp-sems-libsems1-dev_1.6.0-1+0~mr10.3.0.0_amd64.deb 
Selecting previously unselected package ngcp-sems-libsems1-dev.
(Reading database ... 197629 files and directories currently installed.)
Preparing to unpack ngcp-sems-libsems1-dev_1.6.0-1+0~mr10.3.0.0_amd64.deb ...
Unpacking ngcp-sems-libsems1-dev (1:1.6.0-1+0~mr10.3.0.0) ...
Setting up ngcp-sems-libsems1-dev (1:1.6.0-1+0~mr10.3.0.0) ...
root@sems:/usr/src# dpkg -i ngcp-sems_1.6.0-1+0~mr10.3.0.0_amd64.deb 
(Reading database ... 197772 files and directories currently installed.)
Preparing to unpack ngcp-sems_1.6.0-1+0~mr10.3.0.0_amd64.deb ...
Unpacking ngcp-sems (1:1.6.0-1+0~mr10.3.0.0) over (1:1.6.0-1+0~mr10.3.0.0) ...
dpkg: dependency problems prevent configuration of ngcp-sems:
 ngcp-sems depends on ngcp-prompts; however:
  Package ngcp-prompts is not installed.
 ngcp-sems depends on ngcp-system-tools; however:
  Package ngcp-system-tools is not installed.

where do I find these packets or how do I need to install sems ? 

Best regards, Johan.

**Comment by mika** [comment]
Those dependencies are available from the according NGCP release repositories, e.g. the latest packages for mr10.2 are available at:

* https://deb.sipwise.com/spce/mr10.2/pool/main/n/ngcp-prompts/
* https://deb.sipwise.com/spce/mr10.2/pool/main/n/ngcp-system-tools/

**Comment by taurus-forever** [comment]
Sipwise is using GPL SEMS 1.6 for NGCP CE (community edition) only: https://www.sipwise.com/spce/
Sipwise PRO/Carrier editions are using commercial SEMS 2.3 with high-availability support and many more extra features.
At the moment Sipwise provides SEMS 1.6 best efforts support free of charge.

We recommend including Sipwise APT repository in full and install SEMS with all dependencies from the repo:

> root@spce:~# cat /etc/apt/sources.list.d/*
> # Debian repositories
> deb https://debian.sipwise.com/debian/ bullseye main contrib non-free
> deb https://debian.sipwise.com/debian-security/ bullseye-security main contrib non-free
> deb https://debian.sipwise.com/debian/ bullseye-updates main contrib non-free
> deb https://debian.sipwise.com/debian-debug/ bullseye-debug main contrib non-free
> # Sipwise repository
> deb [arch=amd64] https://deb.sipwise.com/spce/mr10.1.1/ bullseye main
> #deb-src https://deb.sipwise.com/spce/mr10.1.1/ bullseye main
> root@spce:~# 

P.S. mrX.X mentioned above are stabilization releases/repos and not available for public usage,
please use mrX.X.X numbers, like mr10.1.1 (the latest published release): https://sipwise.com/releases/

Feel free to reopen if necessary! Enjoy Sipwise NGCP! :-D

**Comment by bshirazi** [comment]
> Those dependencies are available from the according NGCP release repositories, e.g. the latest packages for mr10.2 are available at:
> 
>     * https://deb.sipwise.com/spce/mr10.2/pool/main/n/ngcp-prompts/
> 
>     * https://deb.sipwise.com/spce/mr10.2/pool/main/n/ngcp-system-tools/

Hi  @taurus-forever 
Sorry for asking here. Is it possible to install SEMS with above repository via packages ?  something like:
apt-get install  sipwise-sems  ?

Regards
Shirazi

**Comment by taurus-forever** [comment]
> Hi @taurus-forever Sorry for asking here. Is it possible to install SEMS with above repository via packages ? something like: apt-get install sipwise-sems ?

Hi, excuse me for delay with a reply.

Sure it is possible:
1) add source file:
> cat "deb [arch=amd64] https://deb.sipwise.com/spce/mr10.2.1/ bullseye main" > /etc/apt/sources.list.d/sipwise.list
2) install apt key: https://deb.sipwise.com/spce/keyring/ngcp-archive-keyring_mr10.2.1.deb
3) apt update
4) apt install ngcp-sems
